//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("GuitarShop", "FK__AcousticG__Guita__145C0A3F", "GuitarShops", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(GuitarShop.GuitarShops), "AcousticGuitars", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GuitarShop.AcousticGuitars), true)]
[assembly: EdmRelationshipAttribute("GuitarShop", "FK__Amplifier__Guita__22AA2996", "GuitarShops", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(GuitarShop.GuitarShops), "Amplifiers", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GuitarShop.Amplifiers), true)]
[assembly: EdmRelationshipAttribute("GuitarShop", "FK__Classical__Guita__1BFD2C07", "GuitarShops", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(GuitarShop.GuitarShops), "ClassicalGuitars", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GuitarShop.ClassicalGuitars), true)]
[assembly: EdmRelationshipAttribute("GuitarShop", "FK__Contacts__guitar__31EC6D26", "GuitarShops", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(GuitarShop.GuitarShops), "Contacts", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GuitarShop.Contacts), true)]
[assembly: EdmRelationshipAttribute("GuitarShop", "FK__ElectricG__Guita__0519C6AF", "GuitarShops", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(GuitarShop.GuitarShops), "ElectricGuitars", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GuitarShop.ElectricGuitars), true)]
[assembly: EdmRelationshipAttribute("GuitarShop", "FK__Pickups__guitarI__0EA330E9", "ElectricGuitars", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(GuitarShop.ElectricGuitars), "Pickups", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GuitarShop.Pickups), true)]
[assembly: EdmRelationshipAttribute("GuitarShop", "FK__Strings__GuitarS__2A4B4B5E", "GuitarShops", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(GuitarShop.GuitarShops), "Strings", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GuitarShop.Strings), true)]

#endregion

namespace GuitarShop
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class GuitarShopEntities6 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new GuitarShopEntities6 object using the connection string found in the 'GuitarShopEntities6' section of the application configuration file.
        /// </summary>
        public GuitarShopEntities6() : base("name=GuitarShopEntities6", "GuitarShopEntities6")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GuitarShopEntities6 object.
        /// </summary>
        public GuitarShopEntities6(string connectionString) : base(connectionString, "GuitarShopEntities6")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GuitarShopEntities6 object.
        /// </summary>
        public GuitarShopEntities6(EntityConnection connection) : base(connection, "GuitarShopEntities6")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AcousticGuitars> AcousticGuitars
        {
            get
            {
                if ((_AcousticGuitars == null))
                {
                    _AcousticGuitars = base.CreateObjectSet<AcousticGuitars>("AcousticGuitars");
                }
                return _AcousticGuitars;
            }
        }
        private ObjectSet<AcousticGuitars> _AcousticGuitars;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Amplifiers> Amplifiers
        {
            get
            {
                if ((_Amplifiers == null))
                {
                    _Amplifiers = base.CreateObjectSet<Amplifiers>("Amplifiers");
                }
                return _Amplifiers;
            }
        }
        private ObjectSet<Amplifiers> _Amplifiers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ClassicalGuitars> ClassicalGuitars
        {
            get
            {
                if ((_ClassicalGuitars == null))
                {
                    _ClassicalGuitars = base.CreateObjectSet<ClassicalGuitars>("ClassicalGuitars");
                }
                return _ClassicalGuitars;
            }
        }
        private ObjectSet<ClassicalGuitars> _ClassicalGuitars;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Contacts> Contacts
        {
            get
            {
                if ((_Contacts == null))
                {
                    _Contacts = base.CreateObjectSet<Contacts>("Contacts");
                }
                return _Contacts;
            }
        }
        private ObjectSet<Contacts> _Contacts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ElectricGuitars> ElectricGuitars
        {
            get
            {
                if ((_ElectricGuitars == null))
                {
                    _ElectricGuitars = base.CreateObjectSet<ElectricGuitars>("ElectricGuitars");
                }
                return _ElectricGuitars;
            }
        }
        private ObjectSet<ElectricGuitars> _ElectricGuitars;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GuitarShops> GuitarShops
        {
            get
            {
                if ((_GuitarShops == null))
                {
                    _GuitarShops = base.CreateObjectSet<GuitarShops>("GuitarShops");
                }
                return _GuitarShops;
            }
        }
        private ObjectSet<GuitarShops> _GuitarShops;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Pickups> Pickups
        {
            get
            {
                if ((_Pickups == null))
                {
                    _Pickups = base.CreateObjectSet<Pickups>("Pickups");
                }
                return _Pickups;
            }
        }
        private ObjectSet<Pickups> _Pickups;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Strings> Strings
        {
            get
            {
                if ((_Strings == null))
                {
                    _Strings = base.CreateObjectSet<Strings>("Strings");
                }
                return _Strings;
            }
        }
        private ObjectSet<Strings> _Strings;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AcousticGuitars EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAcousticGuitars(AcousticGuitars acousticGuitars)
        {
            base.AddObject("AcousticGuitars", acousticGuitars);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Amplifiers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAmplifiers(Amplifiers amplifiers)
        {
            base.AddObject("Amplifiers", amplifiers);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ClassicalGuitars EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClassicalGuitars(ClassicalGuitars classicalGuitars)
        {
            base.AddObject("ClassicalGuitars", classicalGuitars);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Contacts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToContacts(Contacts contacts)
        {
            base.AddObject("Contacts", contacts);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ElectricGuitars EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToElectricGuitars(ElectricGuitars electricGuitars)
        {
            base.AddObject("ElectricGuitars", electricGuitars);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GuitarShops EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGuitarShops(GuitarShops guitarShops)
        {
            base.AddObject("GuitarShops", guitarShops);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Pickups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPickups(Pickups pickups)
        {
            base.AddObject("Pickups", pickups);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Strings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStrings(Strings strings)
        {
            base.AddObject("Strings", strings);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GuitarShop", Name="AcousticGuitars")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AcousticGuitars : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AcousticGuitars object.
        /// </summary>
        /// <param name="guitarID">Initial value of the guitarID property.</param>
        public static AcousticGuitars CreateAcousticGuitars(global::System.Int32 guitarID)
        {
            AcousticGuitars acousticGuitars = new AcousticGuitars();
            acousticGuitars.guitarID = guitarID;
            return acousticGuitars;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 guitarID
        {
            get
            {
                return _guitarID;
            }
            set
            {
                if (_guitarID != value)
                {
                    OnguitarIDChanging(value);
                    ReportPropertyChanging("guitarID");
                    _guitarID = StructuralObject.SetValidValue(value, "guitarID");
                    ReportPropertyChanged("guitarID");
                    OnguitarIDChanged();
                }
            }
        }
        private global::System.Int32 _guitarID;
        partial void OnguitarIDChanging(global::System.Int32 value);
        partial void OnguitarIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GuitarShopID
        {
            get
            {
                return _GuitarShopID;
            }
            set
            {
                OnGuitarShopIDChanging(value);
                ReportPropertyChanging("GuitarShopID");
                _GuitarShopID = StructuralObject.SetValidValue(value, "GuitarShopID");
                ReportPropertyChanged("GuitarShopID");
                OnGuitarShopIDChanged();
            }
        }
        private Nullable<global::System.Int32> _GuitarShopID;
        partial void OnGuitarShopIDChanging(Nullable<global::System.Int32> value);
        partial void OnGuitarShopIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String electro_acoustic
        {
            get
            {
                return _electro_acoustic;
            }
            set
            {
                Onelectro_acousticChanging(value);
                ReportPropertyChanging("electro_acoustic");
                _electro_acoustic = StructuralObject.SetValidValue(value, true, "electro_acoustic");
                ReportPropertyChanged("electro_acoustic");
                Onelectro_acousticChanged();
            }
        }
        private global::System.String _electro_acoustic;
        partial void Onelectro_acousticChanging(global::System.String value);
        partial void Onelectro_acousticChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true, "description");
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String manufacturer
        {
            get
            {
                return _manufacturer;
            }
            set
            {
                OnmanufacturerChanging(value);
                ReportPropertyChanging("manufacturer");
                _manufacturer = StructuralObject.SetValidValue(value, true, "manufacturer");
                ReportPropertyChanged("manufacturer");
                OnmanufacturerChanged();
            }
        }
        private global::System.String _manufacturer;
        partial void OnmanufacturerChanging(global::System.String value);
        partial void OnmanufacturerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String model
        {
            get
            {
                return _model;
            }
            set
            {
                OnmodelChanging(value);
                ReportPropertyChanging("model");
                _model = StructuralObject.SetValidValue(value, true, "model");
                ReportPropertyChanged("model");
                OnmodelChanged();
            }
        }
        private global::System.String _model;
        partial void OnmodelChanging(global::System.String value);
        partial void OnmodelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> price_value
        {
            get
            {
                return _price_value;
            }
            set
            {
                Onprice_valueChanging(value);
                ReportPropertyChanging("price_value");
                _price_value = StructuralObject.SetValidValue(value, "price_value");
                ReportPropertyChanged("price_value");
                Onprice_valueChanged();
            }
        }
        private Nullable<global::System.Double> _price_value;
        partial void Onprice_valueChanging(Nullable<global::System.Double> value);
        partial void Onprice_valueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String price_currency
        {
            get
            {
                return _price_currency;
            }
            set
            {
                Onprice_currencyChanging(value);
                ReportPropertyChanging("price_currency");
                _price_currency = StructuralObject.SetValidValue(value, true, "price_currency");
                ReportPropertyChanged("price_currency");
                Onprice_currencyChanged();
            }
        }
        private global::System.String _price_currency;
        partial void Onprice_currencyChanging(global::System.String value);
        partial void Onprice_currencyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String body
        {
            get
            {
                return _body;
            }
            set
            {
                OnbodyChanging(value);
                ReportPropertyChanging("body");
                _body = StructuralObject.SetValidValue(value, true, "body");
                ReportPropertyChanged("body");
                OnbodyChanged();
            }
        }
        private global::System.String _body;
        partial void OnbodyChanging(global::System.String value);
        partial void OnbodyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> number_strings
        {
            get
            {
                return _number_strings;
            }
            set
            {
                Onnumber_stringsChanging(value);
                ReportPropertyChanging("number_strings");
                _number_strings = StructuralObject.SetValidValue(value, "number_strings");
                ReportPropertyChanged("number_strings");
                Onnumber_stringsChanged();
            }
        }
        private Nullable<global::System.Byte> _number_strings;
        partial void Onnumber_stringsChanging(Nullable<global::System.Byte> value);
        partial void Onnumber_stringsChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GuitarShop", "FK__AcousticG__Guita__145C0A3F", "GuitarShops")]
        public GuitarShops GuitarShop
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GuitarShops>("GuitarShop.FK__AcousticG__Guita__145C0A3F", "GuitarShops").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GuitarShops>("GuitarShop.FK__AcousticG__Guita__145C0A3F", "GuitarShops").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GuitarShops> GuitarShopReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GuitarShops>("GuitarShop.FK__AcousticG__Guita__145C0A3F", "GuitarShops");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GuitarShops>("GuitarShop.FK__AcousticG__Guita__145C0A3F", "GuitarShops", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GuitarShop", Name="Amplifiers")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Amplifiers : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Amplifiers object.
        /// </summary>
        /// <param name="ampID">Initial value of the ampID property.</param>
        public static Amplifiers CreateAmplifiers(global::System.Int32 ampID)
        {
            Amplifiers amplifiers = new Amplifiers();
            amplifiers.ampID = ampID;
            return amplifiers;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ampID
        {
            get
            {
                return _ampID;
            }
            set
            {
                if (_ampID != value)
                {
                    OnampIDChanging(value);
                    ReportPropertyChanging("ampID");
                    _ampID = StructuralObject.SetValidValue(value, "ampID");
                    ReportPropertyChanged("ampID");
                    OnampIDChanged();
                }
            }
        }
        private global::System.Int32 _ampID;
        partial void OnampIDChanging(global::System.Int32 value);
        partial void OnampIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GuitarShopID
        {
            get
            {
                return _GuitarShopID;
            }
            set
            {
                OnGuitarShopIDChanging(value);
                ReportPropertyChanging("GuitarShopID");
                _GuitarShopID = StructuralObject.SetValidValue(value, "GuitarShopID");
                ReportPropertyChanged("GuitarShopID");
                OnGuitarShopIDChanged();
            }
        }
        private Nullable<global::System.Int32> _GuitarShopID;
        partial void OnGuitarShopIDChanging(Nullable<global::System.Int32> value);
        partial void OnGuitarShopIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true, "description");
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String manufacturer
        {
            get
            {
                return _manufacturer;
            }
            set
            {
                OnmanufacturerChanging(value);
                ReportPropertyChanging("manufacturer");
                _manufacturer = StructuralObject.SetValidValue(value, true, "manufacturer");
                ReportPropertyChanged("manufacturer");
                OnmanufacturerChanged();
            }
        }
        private global::System.String _manufacturer;
        partial void OnmanufacturerChanging(global::System.String value);
        partial void OnmanufacturerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String model
        {
            get
            {
                return _model;
            }
            set
            {
                OnmodelChanging(value);
                ReportPropertyChanging("model");
                _model = StructuralObject.SetValidValue(value, true, "model");
                ReportPropertyChanged("model");
                OnmodelChanged();
            }
        }
        private global::System.String _model;
        partial void OnmodelChanging(global::System.String value);
        partial void OnmodelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> price_value
        {
            get
            {
                return _price_value;
            }
            set
            {
                Onprice_valueChanging(value);
                ReportPropertyChanging("price_value");
                _price_value = StructuralObject.SetValidValue(value, "price_value");
                ReportPropertyChanged("price_value");
                Onprice_valueChanged();
            }
        }
        private Nullable<global::System.Double> _price_value;
        partial void Onprice_valueChanging(Nullable<global::System.Double> value);
        partial void Onprice_valueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String price_currency
        {
            get
            {
                return _price_currency;
            }
            set
            {
                Onprice_currencyChanging(value);
                ReportPropertyChanging("price_currency");
                _price_currency = StructuralObject.SetValidValue(value, true, "price_currency");
                ReportPropertyChanged("price_currency");
                Onprice_currencyChanged();
            }
        }
        private global::System.String _price_currency;
        partial void Onprice_currencyChanging(global::System.String value);
        partial void Onprice_currencyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> power
        {
            get
            {
                return _power;
            }
            set
            {
                OnpowerChanging(value);
                ReportPropertyChanging("power");
                _power = StructuralObject.SetValidValue(value, "power");
                ReportPropertyChanged("power");
                OnpowerChanged();
            }
        }
        private Nullable<global::System.Double> _power;
        partial void OnpowerChanging(Nullable<global::System.Double> value);
        partial void OnpowerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String power_unit
        {
            get
            {
                return _power_unit;
            }
            set
            {
                Onpower_unitChanging(value);
                ReportPropertyChanging("power_unit");
                _power_unit = StructuralObject.SetValidValue(value, true, "power_unit");
                ReportPropertyChanged("power_unit");
                Onpower_unitChanged();
            }
        }
        private global::System.String _power_unit;
        partial void Onpower_unitChanging(global::System.String value);
        partial void Onpower_unitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String amplifier_type
        {
            get
            {
                return _amplifier_type;
            }
            set
            {
                Onamplifier_typeChanging(value);
                ReportPropertyChanging("amplifier_type");
                _amplifier_type = StructuralObject.SetValidValue(value, true, "amplifier_type");
                ReportPropertyChanged("amplifier_type");
                Onamplifier_typeChanged();
            }
        }
        private global::System.String _amplifier_type;
        partial void Onamplifier_typeChanging(global::System.String value);
        partial void Onamplifier_typeChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GuitarShop", "FK__Amplifier__Guita__22AA2996", "GuitarShops")]
        public GuitarShops GuitarShop
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GuitarShops>("GuitarShop.FK__Amplifier__Guita__22AA2996", "GuitarShops").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GuitarShops>("GuitarShop.FK__Amplifier__Guita__22AA2996", "GuitarShops").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GuitarShops> GuitarShopReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GuitarShops>("GuitarShop.FK__Amplifier__Guita__22AA2996", "GuitarShops");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GuitarShops>("GuitarShop.FK__Amplifier__Guita__22AA2996", "GuitarShops", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GuitarShop", Name="ClassicalGuitars")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ClassicalGuitars : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ClassicalGuitars object.
        /// </summary>
        /// <param name="guitarID">Initial value of the guitarID property.</param>
        public static ClassicalGuitars CreateClassicalGuitars(global::System.Int32 guitarID)
        {
            ClassicalGuitars classicalGuitars = new ClassicalGuitars();
            classicalGuitars.guitarID = guitarID;
            return classicalGuitars;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 guitarID
        {
            get
            {
                return _guitarID;
            }
            set
            {
                if (_guitarID != value)
                {
                    OnguitarIDChanging(value);
                    ReportPropertyChanging("guitarID");
                    _guitarID = StructuralObject.SetValidValue(value, "guitarID");
                    ReportPropertyChanged("guitarID");
                    OnguitarIDChanged();
                }
            }
        }
        private global::System.Int32 _guitarID;
        partial void OnguitarIDChanging(global::System.Int32 value);
        partial void OnguitarIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GuitarShopID
        {
            get
            {
                return _GuitarShopID;
            }
            set
            {
                OnGuitarShopIDChanging(value);
                ReportPropertyChanging("GuitarShopID");
                _GuitarShopID = StructuralObject.SetValidValue(value, "GuitarShopID");
                ReportPropertyChanged("GuitarShopID");
                OnGuitarShopIDChanged();
            }
        }
        private Nullable<global::System.Int32> _GuitarShopID;
        partial void OnGuitarShopIDChanging(Nullable<global::System.Int32> value);
        partial void OnGuitarShopIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true, "description");
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String manufacturer
        {
            get
            {
                return _manufacturer;
            }
            set
            {
                OnmanufacturerChanging(value);
                ReportPropertyChanging("manufacturer");
                _manufacturer = StructuralObject.SetValidValue(value, true, "manufacturer");
                ReportPropertyChanged("manufacturer");
                OnmanufacturerChanged();
            }
        }
        private global::System.String _manufacturer;
        partial void OnmanufacturerChanging(global::System.String value);
        partial void OnmanufacturerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String model
        {
            get
            {
                return _model;
            }
            set
            {
                OnmodelChanging(value);
                ReportPropertyChanging("model");
                _model = StructuralObject.SetValidValue(value, true, "model");
                ReportPropertyChanged("model");
                OnmodelChanged();
            }
        }
        private global::System.String _model;
        partial void OnmodelChanging(global::System.String value);
        partial void OnmodelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> price_value
        {
            get
            {
                return _price_value;
            }
            set
            {
                Onprice_valueChanging(value);
                ReportPropertyChanging("price_value");
                _price_value = StructuralObject.SetValidValue(value, "price_value");
                ReportPropertyChanged("price_value");
                Onprice_valueChanged();
            }
        }
        private Nullable<global::System.Double> _price_value;
        partial void Onprice_valueChanging(Nullable<global::System.Double> value);
        partial void Onprice_valueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String price_currency
        {
            get
            {
                return _price_currency;
            }
            set
            {
                Onprice_currencyChanging(value);
                ReportPropertyChanging("price_currency");
                _price_currency = StructuralObject.SetValidValue(value, true, "price_currency");
                ReportPropertyChanged("price_currency");
                Onprice_currencyChanged();
            }
        }
        private global::System.String _price_currency;
        partial void Onprice_currencyChanging(global::System.String value);
        partial void Onprice_currencyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String electro_acoustic
        {
            get
            {
                return _electro_acoustic;
            }
            set
            {
                Onelectro_acousticChanging(value);
                ReportPropertyChanging("electro_acoustic");
                _electro_acoustic = StructuralObject.SetValidValue(value, true, "electro_acoustic");
                ReportPropertyChanged("electro_acoustic");
                Onelectro_acousticChanged();
            }
        }
        private global::System.String _electro_acoustic;
        partial void Onelectro_acousticChanging(global::System.String value);
        partial void Onelectro_acousticChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GuitarShop", "FK__Classical__Guita__1BFD2C07", "GuitarShops")]
        public GuitarShops GuitarShop
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GuitarShops>("GuitarShop.FK__Classical__Guita__1BFD2C07", "GuitarShops").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GuitarShops>("GuitarShop.FK__Classical__Guita__1BFD2C07", "GuitarShops").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GuitarShops> GuitarShopReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GuitarShops>("GuitarShop.FK__Classical__Guita__1BFD2C07", "GuitarShops");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GuitarShops>("GuitarShop.FK__Classical__Guita__1BFD2C07", "GuitarShops", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GuitarShop", Name="Contacts")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Contacts : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Contacts object.
        /// </summary>
        /// <param name="contactsID">Initial value of the contactsID property.</param>
        public static Contacts CreateContacts(global::System.Int32 contactsID)
        {
            Contacts contacts = new Contacts();
            contacts.contactsID = contactsID;
            return contacts;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> guitar_shopID
        {
            get
            {
                return _guitar_shopID;
            }
            set
            {
                Onguitar_shopIDChanging(value);
                ReportPropertyChanging("guitar_shopID");
                _guitar_shopID = StructuralObject.SetValidValue(value, "guitar_shopID");
                ReportPropertyChanged("guitar_shopID");
                Onguitar_shopIDChanged();
            }
        }
        private Nullable<global::System.Int32> _guitar_shopID;
        partial void Onguitar_shopIDChanging(Nullable<global::System.Int32> value);
        partial void Onguitar_shopIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 contactsID
        {
            get
            {
                return _contactsID;
            }
            set
            {
                if (_contactsID != value)
                {
                    OncontactsIDChanging(value);
                    ReportPropertyChanging("contactsID");
                    _contactsID = StructuralObject.SetValidValue(value, "contactsID");
                    ReportPropertyChanged("contactsID");
                    OncontactsIDChanged();
                }
            }
        }
        private global::System.Int32 _contactsID;
        partial void OncontactsIDChanging(global::System.Int32 value);
        partial void OncontactsIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String adress
        {
            get
            {
                return _adress;
            }
            set
            {
                OnadressChanging(value);
                ReportPropertyChanging("adress");
                _adress = StructuralObject.SetValidValue(value, true, "adress");
                ReportPropertyChanged("adress");
                OnadressChanged();
            }
        }
        private global::System.String _adress;
        partial void OnadressChanging(global::System.String value);
        partial void OnadressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, true, "phone");
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true, "email");
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String website
        {
            get
            {
                return _website;
            }
            set
            {
                OnwebsiteChanging(value);
                ReportPropertyChanging("website");
                _website = StructuralObject.SetValidValue(value, true, "website");
                ReportPropertyChanged("website");
                OnwebsiteChanged();
            }
        }
        private global::System.String _website;
        partial void OnwebsiteChanging(global::System.String value);
        partial void OnwebsiteChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GuitarShop", "FK__Contacts__guitar__31EC6D26", "GuitarShops")]
        public GuitarShops GuitarShop
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GuitarShops>("GuitarShop.FK__Contacts__guitar__31EC6D26", "GuitarShops").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GuitarShops>("GuitarShop.FK__Contacts__guitar__31EC6D26", "GuitarShops").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GuitarShops> GuitarShopReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GuitarShops>("GuitarShop.FK__Contacts__guitar__31EC6D26", "GuitarShops");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GuitarShops>("GuitarShop.FK__Contacts__guitar__31EC6D26", "GuitarShops", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GuitarShop", Name="ElectricGuitars")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ElectricGuitars : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ElectricGuitars object.
        /// </summary>
        /// <param name="guitarID">Initial value of the guitarID property.</param>
        public static ElectricGuitars CreateElectricGuitars(global::System.Int32 guitarID)
        {
            ElectricGuitars electricGuitars = new ElectricGuitars();
            electricGuitars.guitarID = guitarID;
            return electricGuitars;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 guitarID
        {
            get
            {
                return _guitarID;
            }
            set
            {
                if (_guitarID != value)
                {
                    OnguitarIDChanging(value);
                    ReportPropertyChanging("guitarID");
                    _guitarID = StructuralObject.SetValidValue(value, "guitarID");
                    ReportPropertyChanged("guitarID");
                    OnguitarIDChanged();
                }
            }
        }
        private global::System.Int32 _guitarID;
        partial void OnguitarIDChanging(global::System.Int32 value);
        partial void OnguitarIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GuitarShopID
        {
            get
            {
                return _GuitarShopID;
            }
            set
            {
                OnGuitarShopIDChanging(value);
                ReportPropertyChanging("GuitarShopID");
                _GuitarShopID = StructuralObject.SetValidValue(value, "GuitarShopID");
                ReportPropertyChanged("GuitarShopID");
                OnGuitarShopIDChanged();
            }
        }
        private Nullable<global::System.Int32> _GuitarShopID;
        partial void OnGuitarShopIDChanging(Nullable<global::System.Int32> value);
        partial void OnGuitarShopIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true, "description");
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String manufacturer
        {
            get
            {
                return _manufacturer;
            }
            set
            {
                OnmanufacturerChanging(value);
                ReportPropertyChanging("manufacturer");
                _manufacturer = StructuralObject.SetValidValue(value, true, "manufacturer");
                ReportPropertyChanged("manufacturer");
                OnmanufacturerChanged();
            }
        }
        private global::System.String _manufacturer;
        partial void OnmanufacturerChanging(global::System.String value);
        partial void OnmanufacturerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String model
        {
            get
            {
                return _model;
            }
            set
            {
                OnmodelChanging(value);
                ReportPropertyChanging("model");
                _model = StructuralObject.SetValidValue(value, true, "model");
                ReportPropertyChanged("model");
                OnmodelChanged();
            }
        }
        private global::System.String _model;
        partial void OnmodelChanging(global::System.String value);
        partial void OnmodelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> number_strings
        {
            get
            {
                return _number_strings;
            }
            set
            {
                Onnumber_stringsChanging(value);
                ReportPropertyChanging("number_strings");
                _number_strings = StructuralObject.SetValidValue(value, "number_strings");
                ReportPropertyChanged("number_strings");
                Onnumber_stringsChanged();
            }
        }
        private Nullable<global::System.Byte> _number_strings;
        partial void Onnumber_stringsChanging(Nullable<global::System.Byte> value);
        partial void Onnumber_stringsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> number_frets
        {
            get
            {
                return _number_frets;
            }
            set
            {
                Onnumber_fretsChanging(value);
                ReportPropertyChanging("number_frets");
                _number_frets = StructuralObject.SetValidValue(value, "number_frets");
                ReportPropertyChanged("number_frets");
                Onnumber_fretsChanged();
            }
        }
        private Nullable<global::System.Byte> _number_frets;
        partial void Onnumber_fretsChanging(Nullable<global::System.Byte> value);
        partial void Onnumber_fretsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> price_value
        {
            get
            {
                return _price_value;
            }
            set
            {
                Onprice_valueChanging(value);
                ReportPropertyChanging("price_value");
                _price_value = StructuralObject.SetValidValue(value, "price_value");
                ReportPropertyChanged("price_value");
                Onprice_valueChanged();
            }
        }
        private Nullable<global::System.Double> _price_value;
        partial void Onprice_valueChanging(Nullable<global::System.Double> value);
        partial void Onprice_valueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String price_currency
        {
            get
            {
                return _price_currency;
            }
            set
            {
                Onprice_currencyChanging(value);
                ReportPropertyChanging("price_currency");
                _price_currency = StructuralObject.SetValidValue(value, true, "price_currency");
                ReportPropertyChanged("price_currency");
                Onprice_currencyChanged();
            }
        }
        private global::System.String _price_currency;
        partial void Onprice_currencyChanging(global::System.String value);
        partial void Onprice_currencyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String body
        {
            get
            {
                return _body;
            }
            set
            {
                OnbodyChanging(value);
                ReportPropertyChanging("body");
                _body = StructuralObject.SetValidValue(value, true, "body");
                ReportPropertyChanged("body");
                OnbodyChanged();
            }
        }
        private global::System.String _body;
        partial void OnbodyChanging(global::System.String value);
        partial void OnbodyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pickguard
        {
            get
            {
                return _pickguard;
            }
            set
            {
                OnpickguardChanging(value);
                ReportPropertyChanging("pickguard");
                _pickguard = StructuralObject.SetValidValue(value, true, "pickguard");
                ReportPropertyChanged("pickguard");
                OnpickguardChanged();
            }
        }
        private global::System.String _pickguard;
        partial void OnpickguardChanging(global::System.String value);
        partial void OnpickguardChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tremolo
        {
            get
            {
                return _tremolo;
            }
            set
            {
                OntremoloChanging(value);
                ReportPropertyChanging("tremolo");
                _tremolo = StructuralObject.SetValidValue(value, true, "tremolo");
                ReportPropertyChanged("tremolo");
                OntremoloChanged();
            }
        }
        private global::System.String _tremolo;
        partial void OntremoloChanging(global::System.String value);
        partial void OntremoloChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GuitarShop", "FK__ElectricG__Guita__0519C6AF", "GuitarShops")]
        public GuitarShops GuitarShop
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GuitarShops>("GuitarShop.FK__ElectricG__Guita__0519C6AF", "GuitarShops").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GuitarShops>("GuitarShop.FK__ElectricG__Guita__0519C6AF", "GuitarShops").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GuitarShops> GuitarShopReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GuitarShops>("GuitarShop.FK__ElectricG__Guita__0519C6AF", "GuitarShops");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GuitarShops>("GuitarShop.FK__ElectricG__Guita__0519C6AF", "GuitarShops", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GuitarShop", "FK__Pickups__guitarI__0EA330E9", "Pickups")]
        public EntityCollection<Pickups> Pickups
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Pickups>("GuitarShop.FK__Pickups__guitarI__0EA330E9", "Pickups");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Pickups>("GuitarShop.FK__Pickups__guitarI__0EA330E9", "Pickups", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GuitarShop", Name="GuitarShops")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GuitarShops : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GuitarShops object.
        /// </summary>
        /// <param name="guitarShopID">Initial value of the GuitarShopID property.</param>
        public static GuitarShops CreateGuitarShops(global::System.Int32 guitarShopID)
        {
            GuitarShops guitarShops = new GuitarShops();
            guitarShops.GuitarShopID = guitarShopID;
            return guitarShops;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GuitarShopID
        {
            get
            {
                return _GuitarShopID;
            }
            set
            {
                if (_GuitarShopID != value)
                {
                    OnGuitarShopIDChanging(value);
                    ReportPropertyChanging("GuitarShopID");
                    _GuitarShopID = StructuralObject.SetValidValue(value, "GuitarShopID");
                    ReportPropertyChanged("GuitarShopID");
                    OnGuitarShopIDChanged();
                }
            }
        }
        private global::System.Int32 _GuitarShopID;
        partial void OnGuitarShopIDChanging(global::System.Int32 value);
        partial void OnGuitarShopIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GuitarShop", "FK__AcousticG__Guita__145C0A3F", "AcousticGuitars")]
        public EntityCollection<AcousticGuitars> AcousticGuitars
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<AcousticGuitars>("GuitarShop.FK__AcousticG__Guita__145C0A3F", "AcousticGuitars");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<AcousticGuitars>("GuitarShop.FK__AcousticG__Guita__145C0A3F", "AcousticGuitars", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GuitarShop", "FK__Amplifier__Guita__22AA2996", "Amplifiers")]
        public EntityCollection<Amplifiers> Amplifiers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Amplifiers>("GuitarShop.FK__Amplifier__Guita__22AA2996", "Amplifiers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Amplifiers>("GuitarShop.FK__Amplifier__Guita__22AA2996", "Amplifiers", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GuitarShop", "FK__Classical__Guita__1BFD2C07", "ClassicalGuitars")]
        public EntityCollection<ClassicalGuitars> ClassicalGuitars
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ClassicalGuitars>("GuitarShop.FK__Classical__Guita__1BFD2C07", "ClassicalGuitars");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ClassicalGuitars>("GuitarShop.FK__Classical__Guita__1BFD2C07", "ClassicalGuitars", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GuitarShop", "FK__Contacts__guitar__31EC6D26", "Contacts")]
        public EntityCollection<Contacts> Contacts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Contacts>("GuitarShop.FK__Contacts__guitar__31EC6D26", "Contacts");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Contacts>("GuitarShop.FK__Contacts__guitar__31EC6D26", "Contacts", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GuitarShop", "FK__ElectricG__Guita__0519C6AF", "ElectricGuitars")]
        public EntityCollection<ElectricGuitars> ElectricGuitars
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ElectricGuitars>("GuitarShop.FK__ElectricG__Guita__0519C6AF", "ElectricGuitars");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ElectricGuitars>("GuitarShop.FK__ElectricG__Guita__0519C6AF", "ElectricGuitars", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GuitarShop", "FK__Strings__GuitarS__2A4B4B5E", "Strings")]
        public EntityCollection<Strings> Strings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Strings>("GuitarShop.FK__Strings__GuitarS__2A4B4B5E", "Strings");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Strings>("GuitarShop.FK__Strings__GuitarS__2A4B4B5E", "Strings", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GuitarShop", Name="Pickups")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pickups : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pickups object.
        /// </summary>
        /// <param name="pickupID">Initial value of the pickupID property.</param>
        public static Pickups CreatePickups(global::System.Int32 pickupID)
        {
            Pickups pickups = new Pickups();
            pickups.pickupID = pickupID;
            return pickups;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> guitarID
        {
            get
            {
                return _guitarID;
            }
            set
            {
                OnguitarIDChanging(value);
                ReportPropertyChanging("guitarID");
                _guitarID = StructuralObject.SetValidValue(value, "guitarID");
                ReportPropertyChanged("guitarID");
                OnguitarIDChanged();
            }
        }
        private Nullable<global::System.Int32> _guitarID;
        partial void OnguitarIDChanging(Nullable<global::System.Int32> value);
        partial void OnguitarIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pickupID
        {
            get
            {
                return _pickupID;
            }
            set
            {
                if (_pickupID != value)
                {
                    OnpickupIDChanging(value);
                    ReportPropertyChanging("pickupID");
                    _pickupID = StructuralObject.SetValidValue(value, "pickupID");
                    ReportPropertyChanged("pickupID");
                    OnpickupIDChanged();
                }
            }
        }
        private global::System.Int32 _pickupID;
        partial void OnpickupIDChanging(global::System.Int32 value);
        partial void OnpickupIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pickup_type
        {
            get
            {
                return _pickup_type;
            }
            set
            {
                Onpickup_typeChanging(value);
                ReportPropertyChanging("pickup_type");
                _pickup_type = StructuralObject.SetValidValue(value, true, "pickup_type");
                ReportPropertyChanged("pickup_type");
                Onpickup_typeChanged();
            }
        }
        private global::System.String _pickup_type;
        partial void Onpickup_typeChanging(global::System.String value);
        partial void Onpickup_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pickup_position
        {
            get
            {
                return _pickup_position;
            }
            set
            {
                Onpickup_positionChanging(value);
                ReportPropertyChanging("pickup_position");
                _pickup_position = StructuralObject.SetValidValue(value, true, "pickup_position");
                ReportPropertyChanged("pickup_position");
                Onpickup_positionChanged();
            }
        }
        private global::System.String _pickup_position;
        partial void Onpickup_positionChanging(global::System.String value);
        partial void Onpickup_positionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GuitarShop", "FK__Pickups__guitarI__0EA330E9", "ElectricGuitars")]
        public ElectricGuitars ElectricGuitar
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ElectricGuitars>("GuitarShop.FK__Pickups__guitarI__0EA330E9", "ElectricGuitars").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ElectricGuitars>("GuitarShop.FK__Pickups__guitarI__0EA330E9", "ElectricGuitars").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ElectricGuitars> ElectricGuitarReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ElectricGuitars>("GuitarShop.FK__Pickups__guitarI__0EA330E9", "ElectricGuitars");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ElectricGuitars>("GuitarShop.FK__Pickups__guitarI__0EA330E9", "ElectricGuitars", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GuitarShop", Name="Strings")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Strings : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Strings object.
        /// </summary>
        /// <param name="stringsID">Initial value of the stringsID property.</param>
        public static Strings CreateStrings(global::System.Int32 stringsID)
        {
            Strings strings = new Strings();
            strings.stringsID = stringsID;
            return strings;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 stringsID
        {
            get
            {
                return _stringsID;
            }
            set
            {
                if (_stringsID != value)
                {
                    OnstringsIDChanging(value);
                    ReportPropertyChanging("stringsID");
                    _stringsID = StructuralObject.SetValidValue(value, "stringsID");
                    ReportPropertyChanged("stringsID");
                    OnstringsIDChanged();
                }
            }
        }
        private global::System.Int32 _stringsID;
        partial void OnstringsIDChanging(global::System.Int32 value);
        partial void OnstringsIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GuitarShopID
        {
            get
            {
                return _GuitarShopID;
            }
            set
            {
                OnGuitarShopIDChanging(value);
                ReportPropertyChanging("GuitarShopID");
                _GuitarShopID = StructuralObject.SetValidValue(value, "GuitarShopID");
                ReportPropertyChanged("GuitarShopID");
                OnGuitarShopIDChanged();
            }
        }
        private Nullable<global::System.Int32> _GuitarShopID;
        partial void OnGuitarShopIDChanging(Nullable<global::System.Int32> value);
        partial void OnGuitarShopIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true, "description");
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String manufacturer
        {
            get
            {
                return _manufacturer;
            }
            set
            {
                OnmanufacturerChanging(value);
                ReportPropertyChanging("manufacturer");
                _manufacturer = StructuralObject.SetValidValue(value, true, "manufacturer");
                ReportPropertyChanged("manufacturer");
                OnmanufacturerChanged();
            }
        }
        private global::System.String _manufacturer;
        partial void OnmanufacturerChanging(global::System.String value);
        partial void OnmanufacturerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> price_value
        {
            get
            {
                return _price_value;
            }
            set
            {
                Onprice_valueChanging(value);
                ReportPropertyChanging("price_value");
                _price_value = StructuralObject.SetValidValue(value, "price_value");
                ReportPropertyChanged("price_value");
                Onprice_valueChanged();
            }
        }
        private Nullable<global::System.Double> _price_value;
        partial void Onprice_valueChanging(Nullable<global::System.Double> value);
        partial void Onprice_valueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String price_currency
        {
            get
            {
                return _price_currency;
            }
            set
            {
                Onprice_currencyChanging(value);
                ReportPropertyChanging("price_currency");
                _price_currency = StructuralObject.SetValidValue(value, true, "price_currency");
                ReportPropertyChanged("price_currency");
                Onprice_currencyChanged();
            }
        }
        private global::System.String _price_currency;
        partial void Onprice_currencyChanging(global::System.String value);
        partial void Onprice_currencyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> gauge
        {
            get
            {
                return _gauge;
            }
            set
            {
                OngaugeChanging(value);
                ReportPropertyChanging("gauge");
                _gauge = StructuralObject.SetValidValue(value, "gauge");
                ReportPropertyChanged("gauge");
                OngaugeChanged();
            }
        }
        private Nullable<global::System.Double> _gauge;
        partial void OngaugeChanging(Nullable<global::System.Double> value);
        partial void OngaugeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String strings_type
        {
            get
            {
                return _strings_type;
            }
            set
            {
                Onstrings_typeChanging(value);
                ReportPropertyChanging("strings_type");
                _strings_type = StructuralObject.SetValidValue(value, true, "strings_type");
                ReportPropertyChanged("strings_type");
                Onstrings_typeChanged();
            }
        }
        private global::System.String _strings_type;
        partial void Onstrings_typeChanging(global::System.String value);
        partial void Onstrings_typeChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GuitarShop", "FK__Strings__GuitarS__2A4B4B5E", "GuitarShops")]
        public GuitarShops GuitarShop
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GuitarShops>("GuitarShop.FK__Strings__GuitarS__2A4B4B5E", "GuitarShops").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GuitarShops>("GuitarShop.FK__Strings__GuitarS__2A4B4B5E", "GuitarShops").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GuitarShops> GuitarShopReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GuitarShops>("GuitarShop.FK__Strings__GuitarS__2A4B4B5E", "GuitarShops");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GuitarShops>("GuitarShop.FK__Strings__GuitarS__2A4B4B5E", "GuitarShops", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
